
POST http://localhost:5000/auth/register
Content-Type: application/json
Cookie: 

{
    "username": "adminmanager",
    "password": "admin1601",
    "fullname":"Tran Nhat Duy"
}
###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "adminmanager",
    "password": "admin1601"
}
###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "adminmanager",
    "password": "admin1601",
    "fullname":"Tran Nhat Duy"
}
###
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "username": "adminduy",
    "password": "admin16015"
}
###
POST http://localhost:5000/auth/register
Content-Type: application/json 

{
    
    "username": "userempployee",
    "password": "user12334",
    "fullname": "Le Huu Hoang"
}
###
POST http://localhost:5000/auth/register
Content-Type: application/json 

{
    "username": "useroanh",
    "password": "admin12345",

}
###
POST http://localhost:4000/auth/register
Content-Type: application/json 

{
     "username": "adminchiba",
    "password": "1234567"
}
### 
POST  http://localhost:4000/ai/question
Content-Type: application/json 

{
   "text":"Hi"
}